### ISSUE TITLE
Fix prometheus example docker networking

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java-docs#11]
The prometheus example uses the docker `--network="host"` option, which doesn't work on macs. The example should be updated to work on macs.

_Originally posted by @jkwatson in https://github.com/open-telemetry/opentelemetry-java-docs/pull/10#discussion_r779156723_

**Comment by Roiocam** [comment]
There is a way to access the host by accessing it from inside the container.

At first I used `docker.for.mac.host.internal` on my m1 macbook, but this didn't work on other operating systems like Linux, Windows.

Then I tried `host.docker.internal` and I found that this parameter worked fine on macOS.

So modifying the Prometheus configuration file to make it compatible with multiple systems seems like a good way to go
