### ISSUE TITLE
Need a example for SkyWalking Exporter

### ISSUE THREAD

**Issue by leopardrota** [open-telemetry/opentelemetry-java-docs#124]
I really need an example for SkyWalking Exporter. When I try to explore by myself I even can not find a jar like opentelemetry-exporter-skywalking.

**Comment by trask** [comment]
hi @leopardrota! this is probably a better question to post to the SkyWalking community

**Comment by leopardrota** [comment]
I'm confused now. I thought the fact is OpenTelemetry has done some work for supporting export metrics data to SkyWalking when I found this [readme.md ](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/skywalkingexporter#readme). Have I misunderstood?

**Comment by trask** [comment]
> I'm confused now. I thought the fact is OpenTelemetry has done some work for supporting export metrics data to SkyWalking when I found this [readme.md ](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/skywalkingexporter#readme). Have I misunderstood?

ah, that is for the OpenTelemetry Collector, which supports exporting to lots of different places

the OpenTelemetry Java project doesn't publish a (direct, without going through the OpenTelemetry Collector) SkyWalking exporter

**Comment by leopardrota** [comment]
> > I'm confused now. I thought the fact is OpenTelemetry has done some work for supporting export metrics data to SkyWalking when I found this [readme.md ](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/skywalkingexporter#readme). Have I misunderstood?
> 
> ah, that is for the OpenTelemetry Collector, which supports exporting to lots of different places
> 
> the OpenTelemetry Java project doesn't publish a (direct, without going through the OpenTelemetry Collector) SkyWalking exporter

Thanks for your reply. Do the OpenTelemetry community have plans to develop a jar similar to `opentelemetry-exporter-jaeger` or `opentelemetry-exporter-zipkin` for SkyWalking?

**Comment by mateuszrzeszutek** [comment]
> Thanks for your reply. Do the OpenTelemetry community have plans to develop a jar similar to `opentelemetry-exporter-jaeger` or `opentelemetry-exporter-zipkin` for SkyWalking?

We don't - but if someone happens to do that we'd welcome the addition to our contrib repo.

**Comment by trask** [comment]
hey @leopardrota - jaeger, zipkin and OTLP exporters have been spec'd (and are required to be implemented) by the OpenTelemetry specification, which is why they live in the opentelemetry-java repository. as @mateuszrzeszutek mentioned, other exporters are welcome to be contributed to the opentelemetry-java-contrib repository
