### ISSUE TITLE
[website_docs] Questions about "Getting started", and OTel website 404s for Java docs

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry-java-docs#19]
### Where's the "Getting started" page?

We're aiming for every language SIG to have a **Getting started** page. Java used to have one (see open-telemetry/opentelemetry-java#3070), but then open-telemetry/opentelemetry-java#3081 dropped it and another page:

- `website_docs/getting_started.md` was deleted
- `website_docs/automatic_instrumentation.md` was deleted

I'm seeing that [QUICKSTART.md], now just a placeholder, directs readers to https://opentelemetry.io/docs/java/manual_instrumentation. Might `manual_instrumentation` be a suitable candidate for a **Getting started** page? If not, what do you suggest we do to get a **Getting started** page for OTel Java?

/cc @theletterf -- who is looking into the topic of **Getting started** pages.

### Addressing top OTel website 404s for Java docs

As you can see from https://github.com/open-telemetry/opentelemetry.io/issues/635, the top Java 404s are for the two files mentioned above that were deleted by open-telemetry/opentelemetry-java#3081. When a page is deleted, a redirect target needs to be chosen so that readers who still have a link to the page don't get a 404, page not found error. 

So my question here is, what should the redirect target be for the following OTel website paths:

- `/docs/java/automatic_instrumentation/`?
- `/docs/java/getting_started/`?
   Note that if we recreate a **Getting started** page, then we won't need a redirect target.

/cc @austinlparker 

[QUICKSTART.md]: https://github.com/open-telemetry/opentelemetry-java/blob/main/QUICKSTART.md

**Comment by trask** [comment]
@chalin is there still something that needs to be done for this? thx
