### ISSUE TITLE
Manual Instrumentation of gRPC example does not seem to work.

### ISSUE THREAD

**Issue by psx95** [open-telemetry/opentelemetry-java-docs#48]
The example being discussed is listed [here](https://github.com/open-telemetry/opentelemetry-java-docs/tree/main/grpc).

### The Issue 

The example contained 2 programs - server and the client. While the server ran successfully and showed to be listening for requests on port 50051. The client program was not able to connect to it following the steps in the Readme for the example. 

Both the server and the client were running on the same machine. When attempting the client to run using - 
```
java -cp ./build/libs/opentelemetry-examples-grpc-0.1.0-SNAPSHOT-all.jar io.opentelemetry.example.grpc.HelloWorldClient
```

The following error was displayed - 

```
WARNING: RPC failed: Status{code=UNAVAILABLE, description=io exception, cause=io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Invalid argument: /localhost:50051
Caused by: java.net.ConnectException: connect(..) failed: Invalid argument
```

### Changes required to run the example 
Switching up the grpc and protobuf libraries in the **root** build.gradle, finally worked. The solution was inspired by the accepted answer in this [StackOverflow post](https://stackoverflow.com/questions/72820928/java-net-socketexception-invalid-argument-connect-with-bungeecord/73170621#73170621).

The protoc, protobuf and the grpc library versions have to be compatible with each other. The compatibility matrix is listed on this [gRPC project's GItHub README](https://github.com/grpc/grpc/blob/master/src/php/README.md). 

I used the latest versions listed on this page, though there have been more recent releases for both these libraries. These versions were - 
1. grpc v1.30.0 
2. protobuf v3.12.2 

### Other Information - 
 - The example was attempted on a machine running *Java* version **11.0.3** & *Gradle* version **7.5**
 - Compilation for both client and server was successful.
 - There were 2 clients in the example - normal and streamed, both of them initially showed the same error and both of them started working after applying the change mentioned above. 
 - When run through an IDE the example ran successfully without making the changes mentioned above
   - The IDE used was IntelliJ UE.
   - The run configuration involved using gradle's compileJava task.
   - The run configuration for running the Java client and server remained similar to what is shown in the README for the original example.

**Comment by Woodrow1026** [comment]
I've met same problem
Thanks for your share
