### ISSUE TITLE
Broken link in micrometer-shim README

### ISSUE THREAD

**Issue by zachauten** [open-telemetry/opentelemetry-java-docs#65]
The link to "micrometer1-shim" on the line `This example demonstrates a typical use case of [micrometer1-shim](https://github.com/open-telemetry/opentelemetry-java/tree/main/micrometer1-shim).` in the file [micrometer-shim/README.md](https://github.com/open-telemetry/opentelemetry-java-docs/tree/main/micrometer-shim) is broken. Looks like the folder was moved. I'd open a PR to fix it but i'm not 100% sure what it's supposed to link to now.

Thanks for all the work you guys do on open-telemetry!

**Comment by trask** [comment]
@zachauten thx for reporting this! I will fix in #74
