### ISSUE TITLE
Can we monitor JVM metrics like Heap, GC, Threads in OpenTelemetry agent?

### ISSUE THREAD

**Issue by chandru-kumar** [open-telemetry/opentelemetry-java-docs#84]
Can we monitor JVM metrics like Heap, GC, Threads in OpenTelemetry agent?
I haven't found any example to configure the metrics in agent. I can see the traces and spans exported, But not JVM metrics.

**Comment by mateuszrzeszutek** [comment]
Hey @chandru-kumar ,
I believe Jack has already answered your question in another issue: https://github.com/open-telemetry/opentelemetry-java/issues/5067#issuecomment-1366960994
